config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/queues'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, skip: :all
  root to: 'batch_contexts#new'
  resources :batch_contexts, only: %i[create index new show]
  resources :job_runs, only: [:create, :index, :show] do
    member do
      get :download_log
      get :download_report
      get :discovery_report_summary
      get :progress_log
      get :process_log
    end
  end
  resources :globus, only: [:show, :index, :create]
end

app/models/job_run.rb
# frozen_string_literal: true

# Model class for the database table job_runs;
#  contains information about a specific pre-assembly or discovery report run; parameters used for that run are in the associated BatchContext
#  the user is able to instantiate multiple jobs (the same and/or different types) using the same BatchContext and each will get its own JobRun
class JobRun < ApplicationRecord
  belongs_to :batch_context
  has_many :accessions, dependent: :destroy
  validates :job_type, presence: true
  validates :state, presence: true
  after_initialize :default_enums

  delegate :progress_log_file, :progress_log_file_exists?, to: :batch_context

  enum :job_type, {
    discovery_report: 0,
    preassembly: 1
  }

  state_machine initial: :waiting do
    event :started do
      transition waiting: :running
    end

    # signifies the entire job could not be run (e.g. bad manifest supplied)
    event :failed do
      transition running: :failed
    end

    event :completed do
      transition running: :discovery_report_complete, if: :discovery_report?
      transition running: :preassembly_complete, if: :preassembly?
    end
    after_transition on: [:completed, :failed], do: :send_preassembly_notification

    event :accessioning_completed do
      transition preassembly_complete: :accessioning_complete
    end
    after_transition on: [:accessioning_completed], do: :send_accessioning_notification
  end

  # send to asynchronous processing via correct Job class for job_type
  # @return [ApplicationJob, nil] nil if unpersisted
  def enqueue!
    return nil unless persisted?

    "#{job_type.camelize}Job".constantize.perform_later(self)
  end

  # the states that indicate this job is either not started or is currently running
  def in_progress?
    waiting? || running?
  end

  # indicates if the discovery report job is ready for display and is available (some jobs may fail, leaving no report)
  def report_ready?
    job_type == 'discovery_report' && !in_progress? && output_location && File.exist?(output_location)
  end

  # @return [DiscoveryReport]
  def to_discovery_report
    @to_discovery_report ||= DiscoveryReport.new(batch)
  end

  # return [PreAssembly::Batch]
  def batch
    @batch ||= if batch_context.using_file_manifest
                 PreAssembly::Batch.new(self, file_manifest:)
               else
                 PreAssembly::Batch.new(self)
               end
  end

  def file_manifest
    PreAssembly::FileManifest.new(csv_filename: batch_context.file_manifest_path,
                                  staging_location: batch_context.staging_location)
  end

  def human_state_name
    return super unless with_preassembly_errors? || with_accessioning_errors?

    name = if preassembly_complete? && accessions.empty?
             'Job completed'
           else
             super
           end

    "#{name} (with #{error_label})"
  end

  def with_preassembly_errors?
    error_message.present?
  end

  def with_accessioning_errors?
    accessions.exists?(state: 'failed')
  end

  private

  def error_label
    if discovery_report?
      'errors'
    elsif with_accessioning_errors? && with_preassembly_errors?
      'preassembly and accessioning errors'
    elsif with_accessioning_errors?
      'accessioning errors'
    else
      'preassembly errors'
    end
  end

  def default_enums
    self[:job_type] ||= 0
  end

  def send_preassembly_notification
    # Always send if a discovery report.
    # Only send if preassembly and has errors.
    return if preassembly? && !with_preassembly_errors?

    JobMailer.with(job_run: self).completion_email.deliver_now
  end

  def send_accessioning_notification
    JobMailer.with(job_run: self).accession_completion_email.deliver_now
  end
end

app/controllers/job_runs_controller.rb
# frozen_string_literal: true

class JobRunsController < ApplicationController
  def index
    @job_runs = JobRun.order('created_at desc').page params[:page]
    render 'recent_history' if request.headers['Turbo-Frame']
  end

  def show
    @job_run = JobRun.find(params[:id])
  end

  def create
    raise ActionController::ParameterMissing, :batch_context_id unless job_run_params[:batch_context_id]

    @job_run = JobRun.new(job_run_params)
    if @job_run.save
      @job_run.enqueue!
      flash.now[:success] = 'Success! Your job is queued. A link to job output will be emailed to you upon completion.'
    else
      flash.now[:error] = "Error(s) saving JobRun: #{@job_run.errors}"
    end
    redirect_to(action: 'index')
  end

  def download_log
    @job_run = JobRun.find(params[:id])
    if @job_run.progress_log_file_exists?
      send_file @job_run.progress_log_file
    else
      flash.now[:warning] = 'Progress log file not available.'
      render 'show'
    end
  end

  def download_report
    @job_run = JobRun.find(params[:id])
    if @job_run.output_location
      send_file @job_run.output_location
    else
      flash.now[:warning] = 'Job is not complete. Please check back later.'
      render 'show'
    end
  end

  def discovery_report_summary
    @job_run = JobRun.find(params[:id])
    if @job_run.report_ready?
      @discovery_report = JSON.parse(File.read(@job_run.output_location))
      @structural_has_changed = structural_changed?
    else
      flash.now[:warning] = 'There is no discovery report. Please check back later.'
      render 'show'
    end
  end

  def progress_log
    @job_run = JobRun.find(params[:id])
    if @job_run.progress_log_file_exists?
      @progress_log = YAML.load_stream(File.read(@job_run.progress_log_file)) if @job_run.progress_log_file_exists?
    else
      flash.now[:warning] = 'Progress log file not available.'
      render 'show'
    end
  end

  def process_log
    job_run = JobRun.find(params[:id])
    @accessions = job_run.accessions
    @objects_with_error = job_run.objects_with_error
  end

  private

  def job_run_params
    params.require(:job_run).permit(:batch_context_id, :job_type)
  end

  # This method is used to determine if any rows in the discovery report include file changes.
  # Consider extracting to a service object if we would like to enhance test coverage.
  def structural_changed?
    return false unless @discovery_report

    @discovery_report['rows']&.any? { |druid| druid.key?('file_diffs') }
  end
end

app/views/job_runs/_actions.html.erb
<div class="col-2">
    <%= form_for(@job_run.batch_context.job_runs.new) do |form| %>
    <%= form.hidden_field :batch_context_id, value: @job_run.batch_context.id %>
    <%= form.hidden_field :job_type, value: 'discovery_report' %>
    <%= form.submit 'New Discovery Report', class: 'btn btn-outline' %>
    <% end %>
</div>
<div class="col-2 text-end">
    <%= form_for(@job_run.batch_context.job_runs.new) do |form| %>
    <%= form.hidden_field :batch_context_id, value: @job_run.batch_context.id %>
    <%= form.hidden_field :job_type, value: 'preassembly' %>
    <%= form.submit 'Run Preassembly', class: 'btn btn-sul-dlss' %>
    <% end %>
</div>

app/views/job_runs/_details.html.erb
 <table class="table table-bordered">
    <thead>
        <tr>
            <th colspan="2">Details</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Job type</td>
            <td><%= @job_run.job_type.humanize %></td>
        </tr>
        <tr>
            <td>Created by</td>
            <td><%= @job_run.batch_context.user.sunet_id %></td>
        </tr>
        <tr>
            <td>Created at</td>
            <td><%= @job_run.created_at %></td>
        </tr>
        <tr>
            <td>Updated at</td>
            <td><%= @job_run.updated_at %></td>
        </tr>
        <tr>
            <td>State</td>
            <td><%= @job_run.human_state_name.capitalize %></td>
        </tr>
        <% unless @job_run.error_message.blank? %>
            <tr>
                <td>Errors</td>
                <td><%= @job_run.error_message %></td>
            </tr>
        <% end %>
        <tr>
            <td>Job output log</td>
            <td>
                <% if @job_run.in_progress? %>
                    Job is not yet complete.  Please check back later.
                <% elsif File.exist? @job_run.progress_log_file %>
                    <%= link_to 'Download', download_log_job_run_path(@job_run) %>
                <% else %>
                    No progress log file is available.
                <% end %>
            </td>
        </tr>
        <% if @job_run.report_ready? %>
            <tr>
                <td>Discovery Report</td>
                <td><%= link_to 'Download', download_report_job_run_path(@job_run) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/job_runs/_job_runs.html.erb
<% @job_runs.each do |job_run| %>
    <tr>
    <td><%= link_to "#{job_prefix}#{job_run.id}", job_run, data: { turbo_frame: '_top' } %></td>
    <td><%= job_run.job_type.humanize %></td>
    <td><%= job_run.batch_context.user.sunet_id %></td>
    <td><%= job_run.human_state_name.capitalize %></td>
    <td><%= job_run.created_at.in_time_zone('Pacific Time (US & Canada)').to_fs(:long) %></td>
    </tr>
<% end %>

app/views/job_runs/_mime_type_summary.html.erb
<% mimetypes.each do |mime_type, num| %>
    <%= mime_type %> : <%= num %><br>
<% end %>

app/views/job_runs/_structural_updates_summary.html.erb
<div class="structural-changes">
  <table class="table">
    <caption>Updates from csv</caption>
    <thead class="table">
    <tr>
        <th>Druid</th>
        <th>Filename</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    <% druids.each do |druid| %>
        <% next unless druid['file_diffs'] %>
        <% %w[added_files deleted_files updated_files].each do |status| %>
          <% druid['file_diffs'][status]&.each do |filename| %>
              <tr>
              <td><%= druid['druid'] %></td>
              <td><%= filename %></td>
              <td><%= status.sub('_files', '').capitalize %></td>
              </tr>
          <% end %>
        <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/job_runs/discovery_report_summary.html.erb
<%# In current reports, objects_with_error is an array; in legacy, it was an integer. %>
<% objects_with_error = @discovery_report['summary']['objects_with_error'] %>
<% objects_with_error_size = objects_with_error.is_a?(Array) ? objects_with_error.size : objects_with_error %>
<div class="row mt-5">
  <div class="col-sm-12">
    <h1><%= link_to @job_run.batch_context.project_name, @job_run.batch_context %> by <%= @job_run.batch_context.user.email %></h1>
    <p><%= @job_run.job_type.humanize %> #<%= @job_run.id %></p>
  </div>
</div>
<turbo-frame id="discovery-report-frame">
  <div class="row mt-5">
    <div class="col-12">
      <table class="table">
        <caption>Results summary</caption>
        <thead>
          <tr>
            <th class="text-center">Number of objects</th>
            <th class="text-center">Number with errors</th>
            <th class="text-center">Total size</th>
            <th class="text-center">Started</th>
            <th class="text-center">Run Time</th>
            <th class="text-center">MIME types</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="text-center"><%= @discovery_report['rows'].size %></td>
            <td class="text-center"><%= objects_with_error_size %></td>
            <td class="text-center"><%= number_to_human_size(@discovery_report['summary']['total_size'], precision: 2) %></td>
            <td class="text-center"><%= @discovery_report['summary']['start_time'].to_time.strftime('%-m/%-d/%y %T') %></td>
            <% if @discovery_report['summary']['end_time'] && @discovery_report['summary']['start_time'] # not all older discovery reports have both times available %>
              <td class="text-center"><%= distance_of_time_in_words(@discovery_report['summary']['end_time'].to_time - @discovery_report['summary']['start_time'].to_time) %></td>
            <% else %>
                <td class="text-center">unknown</td>
            <% end %>
            <td><%= render partial: 'mime_type_summary', locals: { mimetypes: @discovery_report['summary']['mimetypes'] } %></td>
          </tr>
        </tbody>
      </table>

      <% if objects_with_error_size.positive? %>
        <table class="table">
          <caption>Errors Summary</caption>
          <thead class="table">
            <tr>
              <th class="text-center">Druid</th>
              <th class="text-center">Errors</th>
              <th class="text-center">Number of files</th>
              <th class="text-center">Files w/o extension</th>
              <th class="text-center">Total Size</th>
              <th class="text-center">MIME types</th>
            </tr>
          </thead>
          <tbody>
        <% @discovery_report['rows'].each do |row|
            next if row['errors'].blank? %>
              <tr>
                <td><%= row['druid'] %></td>
                <td>
                  <% row['errors'].each do |error, val| %>
                    <%= error %> : <%= val %><br>
                  <% end %>
                </td>
                <td class="text-center"><%= row['counts']['files_found'] %></td>
                <td class="text-center"><%= row['counts']['filename_no_extension'] %></td>
                <td class="text-center"><%= number_to_human_size(row['counts']['total_size'], precision: 2) %></td>
                <td><%= render partial: 'mime_type_summary', locals: { mimetypes: row['counts']['mimetypes'] } %></td>
              </tr>
        <% end %>
        </tbody>
        </table>
      <% end %>

      <%= render partial: 'structural_updates_summary', locals: { druids: @discovery_report['rows'] } if @structural_has_changed %>
    </div>
  </div>
</turbo-frame>

app/views/job_runs/index.html.erb
<h1 class="h2">Job Run History</h1>
  <%= link_to '[view queues]', '/queues', target: 'blank' %>
  <%= paginate @job_runs %>

  <table class="table">
    <thead>
      <tr class="text-nowrap">
        <th scope="col">ID</th>
        <th scope="col">Type</th>
        <th scope="col">Creator</th>
        <th scope="col">Status</th>
        <th scope="col">Created At</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'job_runs', job_prefix: 'Job #' %>
   </tbody>
  </table>

<%= paginate @job_runs %>

app/views/job_runs/process_log.html.erb
<turbo-frame id="process-log-frame">
  <div class="row mt-5">
    <div class="col-12">
      <table class="table">
        <caption>Progress Log</caption>
        <thead>
          <tr>
            <th>DRUID</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @objects_with_error.each do |druid| %>
              <tr>
                <td><%= druid %></td>
                <td>Preassembly error</td>
              </tr>
          <% end %>
          <% @accessions.each do |accession| %>
              <tr>
                <td><%= accession.druid %></td>
                <td>
                  <% if accession.in_progress? %>
                    Accessioning in progress
                  <% elsif accession.failed? %>
                    Accessioning failed. See <%= link_to('Argo', "#{Settings.argo_url}view/#{accession.druid}") %>
                  <% else %>
                    Accessioning success
                  <% end %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</turbo-frame>

app/views/job_runs/progress_log.html.erb
<div class="row mt-5">
  <div class="col-sm-12">
    <h1><%= link_to @job_run.project.project_name, @job_run.project %> by <%= @job_run.project.user.email %></h1>
    <p><%= @job_run.job_type.humanize %> #<%= @job_run.id %></p>
  </div>
</div>
<turbo-frame id="progress-log-frame">
  <div class="row mt-5">
    <div class="col-12">
      <table class="table">
        <caption>Progress Log</caption>
        <thead>
          <tr>
            <th class="text-center">DRUID</th>
            <th class="text-center">Status</th>
            <th class="text-center">Discovery Finished</th>
            <th class="text-center">Pre-assembly Finished</th>
            <th class="text-center">Time Started</th>
          </tr>
        </thead>
        <tbody>
          <% @progress_log.each do |row| %>
              <tr>
                  <td class="text-center"><%= row[:pid] %></td>
                  <td class="text-center"><%= row[:status] %></td>
                  <td class="text-center"><%= row[:discovery_finished] %></td>
                  <td class="text-center"><%= row[:pre_assem_finished] %></td>
                  <td class="text-center"><%= row[:timestamp] %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</turbo-frame>

app/views/job_runs/recent_history.html.erb
<turbo-frame id="recent-history" class="w-100">
  <h2 class="h3">Recent jobs</h2>
  <div class="container p-0">
    <table class="table d-inline-block">
        <thead>
          <tr class="text-nowrap">
            <th>Job</th>
            <th>Type</th>
            <th>Created by</th>
            <th>Status</th>
            <th>Created on</th>
          </th>
        </thead>
      <tbody id="job-history-table" class="text-nowrap">
        <%= render 'job_runs', job_prefix: '' %>
       </tbody>
    </table>
  </div>
</turbo-frame>

app/views/job_runs/show.html.erb
<div class="row mt-5">
  <div class="col-sm-12">
    <h1><%= @job_run.job_type.humanize %> #<%= @job_run.id %></h1>
    <p>Project: <%= link_to @job_run.batch_context.project_name, @job_run.batch_context %></p>
  </div>
</div>
<div class="row p-1 pl-5">
  <div class="col-6 ps-0">
    <%= render partial: 'batch_contexts/settings', locals: { batch_context: @job_run.batch_context } %>
  </div>
  <div class="col-6">
    <%= render partial: 'details' %>
  </div>
</div>
<% if @job_run.report_ready? %>
    <turbo-frame id="discovery-report-frame" src="<%= discovery_report_summary_job_run_path(@job_run) %>"></turbo-frame>
<% end %>
<% if @job_run.preassembly? %>
  <turbo-frame id="process-log-frame" src="<%= process_log_job_run_path(@job_run) %>"></turbo-frame>
<% end %>
<div class="row my-5">
  <div class="col-6">
    <%= link_to 'Return to homepage', root_path, class: 'nav-link' %>
  </div>
  <div class="col-6 justify-content-end">
    <%= render partial: 'batch_contexts/actions', locals: { batch_context: @job_run.batch_context } %>
  </div>
</div>