config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/queues'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, skip: :all
  root to: 'batch_contexts#new'
  resources :batch_contexts, only: %i[create index new show]
  resources :job_runs, only: [:create, :index, :show] do
    member do
      get :download_log
      get :download_report
      get :discovery_report_summary
      get :progress_log
      get :process_log
    end
  end
  resources :globus, only: [:show, :index, :create]
end

app/views/shared/_footer.html.erb
<footer role="contentinfo" class="mt-4">
  <section id="pre-footer" class="pt-3 pb-2">
  <div class="container">
    <div class="row">
      <div id="sul-footer-img" class="col-sm-12 col-md-5 col-lg-4 col-xl-3 d-flex justify-content-center justify-content-md-start">
        <%= link_to 'https://library.stanford.edu' do %>
          <%= image_tag 'sul-logo-stacked.svg', alt: 'Stanford Libraries', height: 45 %>
        <% end %>
      </div>
      <div class="col d-flex justify-content-md-start justify-content-center">
        <ul class="list-unstyled d-flex mt-3 mt-md-1 mt-lg-3 ms-xl-3 text-center">
          <li class="mx-2 mx-md-3"><a href="https://library.stanford.edu/libraries-0/branches-and-centers">Hours &amp; locations</a></li>
          <li class="mx-2 mx-md-3"><a href="https://mylibrary.stanford.edu">My Account</a></li>
          <li class="mx-2 mx-md-3"><a href="https://library.stanford.edu/contact-us">Contact us</a></li>
          <li class="mx-2 mx-md-3"><a href="https://library-status.stanford.edu/">System status</a></li>
        </ul>
      </div>
    </div>
  </div>
  </section>
  <div id="su-footer" class="text-white pt-4 pb-4">
    <div class="container d-flex flex-column flex-lg-row align-items-center align-md-normal" title="Common Stanford resources">
      <div class="mt-1 mb-2 align-self-lg-start">
        <a class="su-logo" href="https://www.stanford.edu">Stanford<br><span class="su-logo-university">University</span></a>
      </div>
      <div class="ms-lg-5">
        <nav aria-label="global footer menu" class="d-flex flex-row gap-4 gap-sm-0 flex-sm-column justify-content-center justify-content-lg-start align-items-start align-items-sm-center align-items-lg-start">
          <ul class="justify-content-center justify-content-lg-start fw-semibold gap-sm-2 gap-md-3 gap-lg-4 list-unstyled d-flex flex-column flex-sm-row">
            <li>
              <a href="https://www.stanford.edu">
                Stanford Home<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://visit.stanford.edu/plan/">
                Maps &amp; Directions<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://www.stanford.edu/search/">
                Search Stanford<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://emergency.stanford.edu">
                Emergency Info<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
          </ul>
          <ul class="justify-content-center justify-content-lg-start gap-sm-2 gap-md-3 gap-lg-4 list-unstyled d-flex flex-column flex-sm-row">
            <li>
              <a href="https://www.stanford.edu/site/terms/" title="Terms of use for sites">
                Terms of Use<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://www.stanford.edu/site/privacy/" title="Privacy and cookie policy">
                Privacy<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://uit.stanford.edu/security/copyright-infringement" title="Report alleged copyright infringement">
                Copyright<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://adminguide.stanford.edu/chapter-1/subchapter-5/policy-1-5-4" title="Ownership and use of Stanford trademarks and images">
                Trademarks<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://studentservices.stanford.edu/more-resources/student-policies/non-academic/non-discrimination" title="Non-discrimination policy">
                Non-Discrimination<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://www.stanford.edu/site/accessibility" title="Report web accessibility issues">
                Accessibility<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
          </ul>
        </nav>
        <div class="text-center text-lg-start copyright">
          <span class="text-nowrap">© Stanford University.</span><span class="text-nowrap">&nbsp; Stanford, California 94305.</span>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.erb
<nav class="navbar navbar-expand-sm">
  <a class="navbar-brand" href="#"><%= link_to image_tag('sul-logo.png', height: '30'), :root %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <%= link_to 'Start New Project', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'All Jobs', job_runs_path, class: "nav-link"%>
      </li>
      <li class = "nav-item">
        <%= link_to 'All Projects', batch_contexts_path, class: "nav-link" %>
      </li>
    </ul>
    <div>
      <a class="nav-link" href="https://github.com/sul-dlss/pre-assembly/wiki">Usage Instructions</a>
    </div>
  </div>
</nav>
<div style="background-color: #8c1515; color: white; font-family: serif">
  <h1 class="p-4">Accessioning</h1>
  <%= image_tag("bookheader.png", width: "100%", height: "75") %>
</div>
<% flash.each do |key, value| %>
  <div class="container">
    <div class="alert alert-<%= key %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><i class="fas fa-times"></i></button>
      <%= value %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="mb-4">
  <a href="#content" class="visually-hidden-focusable">Skip to main content</a>
  <div class="container">
    <a class="su-brand-bar__logo" href="https://www.stanford.edu">Stanford University</a>
  </div>
  <div class="bg-navbar">
    <div class="container">
      <nav class="navbar navbar-expand-md navbar-dark topbar" role="navigation">
        <div class="container-fluid">
          <a class="mb-0 navbar-brand navbar-logo" href="https://library.stanford.edu">Stanford Libraries</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#user-util-collapse" data-bs-target="#user-util-collapse" aria-controls="user-util-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-md-end" id="user-util-collapse">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Usage instructions', 'https://github.com/sul-dlss/pre-assembly/wiki', class: 'nav-link text-white' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="al-masthead bg-navbar">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-8 d-flex justify-content-center justify-content-md-start align-items-center">
            <span class="h1">
              <a href="/" class="text-white">Preassembly</a>
              </span>
          </div>
          <nav class="col-md-4 nav-links d-flex justify-content-md-end justify-content-center" aria-label="browse">
            <ul class="navbar-nav">
              <li class="nav-item ">
                <%= link_to 'Start new job', root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item ml-3 ms-3">
                <%= link_to 'All jobs', job_runs_path, class: 'nav-link' %>
              </li>
              <li class="nav-item ml-3 ms-3">
                <%= link_to 'All projects', batch_contexts_path, class: 'nav-link' %>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
</header>

<% flash.each do |key, value| %>
  <div class="container">
   <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= value %>
    </div>
  </div>
<% end %>