config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/queues'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, skip: :all
  root to: 'batch_contexts#new'
  resources :batch_contexts, only: %i[create index new show]
  resources :job_runs, only: [:create, :index, :show] do
    member do
      get :download_log
      get :download_report
      get :discovery_report_summary
      get :progress_log
      get :process_log
    end
  end
  resources :globus, only: [:show, :index, :create]
end

app/models/project.rb
# frozen_string_literal: true

# Model class for the database table projects;
#  contains information needed to run jobs, be they discovery reports or pre_assemble runs
#  The user creates a new Project by filling in the main form in the pre-assembly UI, indicating parameters common to both
#   pre-assembly and discovery report jobs.  They can then run either type of job using these common paramters by clicking a button:
#   this creates a new JobRun, which belongs_to the associated Project.
# rubocop:disable Metrics/ClassLength
class Project < ApplicationRecord
  # an optional manifest that provides additional detail about the files contained in each object: only used for specific jobs
  FILE_MANIFEST_FILE_NAME = 'file_manifest.csv'

  # the manifest specifying objects and associated folders on disk: required to run any job
  OBJECT_MANIFEST_FILE_NAME = 'manifest.csv'

  belongs_to :user
  has_many :job_runs, dependent: :destroy
  after_initialize :normalize_staging_location, :default_enums
  before_save :output_dir_exists!, if: proc { persisted? }
  before_create :output_dir_no_exists!

  validates :staging_location, :processing_configuration, :content_structure, presence: true
  validates :project_name, presence: true, format: { with: /\A[\w-]+\z/,
                                                     message: 'only allows A-Z, a-z, 0-9, hyphen and underscore' }
  validates :staging_style_symlink, :using_file_manifest, inclusion: { in: [true, false] }

  validate :verify_file_manifest_selected_for_media

  validate :verify_staging_location
  validate :verify_staging_location_path
  validate :verify_file_manifest_exists, if: :using_file_manifest

  enum content_structure: {
    'simple_image' => 0,
    'simple_book' => 1,
    'book_as_image' => 2, # Deprecated
    'file' => 3,
    'media' => 4,
    '3d' => 5,
    'document' => 6,
    'maps' => 7,
    'webarchive_seed' => 8,
    'simple_book_rtl' => 9
  }

  enum processing_configuration: {
    'default' => 0,
    'filename' => 1,
    'media_cm_style' => 2, # Deprecated
    'filename_with_ocr' => 3
  }

  accepts_nested_attributes_for :job_runs

  def project_style
    content_structure
  end

  def output_dir
    @output_dir ||= File.join(normalize_dir(Settings.job_output_parent_dir), user.email, project_name)
  end

  def progress_log_file
    @progress_log_file ||= File.join(output_dir, "#{project_name}_progress.yml")
  end

  def progress_log_file_exists?
    progress_log_file && File.exist?(progress_log_file)
  end

  def staging_location_with_path(rel_path)
    File.join(staging_location, rel_path)
  end

  # On first call, loads the manifest data, caches results
  # @return [Array<ActiveSupport::HashWithIndifferentAccess>]
  def object_manifest_rows
    @object_manifest_rows ||= load_object_manifest
  end

  # load the manifest.csv file and verify there is at least one object and the correct header is present
  def load_object_manifest
    raise 'manifest file missing or empty' if !File.exist?(object_manifest_path) || File.empty?(object_manifest_path)

    manifest_rows = CsvImporter.parse_to_hash(object_manifest_path)
    raise 'no rows in manifest or missing header' if manifest_rows.empty?

    columns = manifest_rows.first.keys
    raise 'manifest must have "druid" and "object" columns' unless (%w[druid object] - columns).empty?

    manifest_rows
  end

  def file_manifest_path
    staging_location_with_path(FILE_MANIFEST_FILE_NAME)
  end

  private

  def object_manifest_path
    staging_location_with_path(OBJECT_MANIFEST_FILE_NAME)
  end

  def default_enums
    self[:content_structure] ||= 0
    self[:processing_configuration] ||= 0
  end

  def normalize_dir(dir)
    dir&.chomp('/')
  end

  def normalize_staging_location
    self[:staging_location] = normalize_dir(staging_location)
  end

  def staging_location_path
    return unless staging_location

    Pathname.new(staging_location).expand_path
  end

  def output_dir_exists!
    return if Dir.exist?(output_dir)

    errors.add(:staging_location, "Output directory (#{output_dir}) should already exist, but doesn't")
    throw(:abort)
  end

  def output_dir_no_exists!
    if Dir.exist?(output_dir)
      errors.add(:staging_location, "Output directory (#{output_dir}) should not already exist")
      throw(:abort)
    end
    FileUtils.mkdir_p(output_dir)
  end

  def verify_file_manifest_selected_for_media
    return unless content_structure == 'media' && !using_file_manifest

    errors.add(:content_structure, 'requires a file manifest.  Please select the checkbox and ensure a file manifest is present.')
  end

  def verify_staging_location
    return if errors.key?(:staging_location)
    return errors.add(:staging_location, "'#{staging_location}' not found.") unless File.directory?(staging_location)

    errors.add(:staging_location, "missing manifest: #{object_manifest_path}") unless File.exist?(object_manifest_path)
  end

  def verify_staging_location_path
    return if errors.key?(:staging_location)

    match_flag = nil
    staging_location_path&.ascend do |sub_path|
      next unless ::ALLOWABLE_STAGING_LOCATIONS.include?(sub_path.to_s)

      match_flag = sub_path
      break
    end
    # match_flag = nil means we are not in the sub path, match_flag == staging_location_path means the user only entered the root path.
    return unless match_flag.nil? || match_flag == staging_location_path

    errors.add(:staging_location, 'not a sub directory of allowed parent directories.')
  end

  def verify_file_manifest_exists
    errors.add(:staging_location, "missing or empty file manifest: #{file_manifest_path}") unless File.exist?(file_manifest_path) && !File.empty?(file_manifest_path)
  end
end
# rubocop:enable Metrics/ClassLength

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
    @projects = Project.order(:created_at).page(params[:page])
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new(
      job_runs: [JobRun.new]
    )
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = 'Success! Your job is queued. A link to job output will be emailed to you upon completion.'
      redirect_to controller: 'job_runs', status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project)
          .permit(:project_name, :content_structure, :staging_style_symlink,
                  :processing_configuration, :staging_location, :all_files_public,
                  :using_file_manifest, job_runs_attributes: [:job_type])
          .merge(user: current_user)
  end
end

app/views/projects/_actions.html.erb
<div class="col-2">
    <%= form_for(JobRun.new) do |form| %>
    <%= form.hidden_field :project_id, value: project.id %>
    <%= form.hidden_field :job_type, value: 'discovery_report' %>
    <%= form.submit 'New Discovery Report', class: 'btn btn-outline' %>
    <% end %>
</div>
<div class="col-2 text-end">
    <%= form_for(JobRun.new) do |form| %>
    <%= form.hidden_field :project_id, value: project.id %>
    <%= form.hidden_field :job_type, value: 'preassembly' %>
    <%= form.submit 'Run Preassembly', class: 'btn btn-sul-dlss' %>
    <% end %>
</div>

app/views/projects/_new_bc_form.erb
<h3>Complete the form below</h3>

<%= simple_form_for @project do |form| %>
    <%= form.input :project_name %>

    <%= form.simple_fields_for :job_runs do |jt| %>
        <%= jt.input :job_type, collection:
            [
                ["Pre Assembly Run", "preassembly"],
                ["Discovery Report", "discovery_report"]
            ]
        %>
    <% end %>

    <%= form.input :content_structure, collection:
    [
        ['Image', 'simple_image'],
        ['Book (ltr)', 'simple_book'],
        ['Book (rtl)', 'simple_book_rtl'],
        ['Document', 'document'],
        ['File', 'file'],
        ['Media', 'media'],
        ['3D', '3d'],
        ['Map', 'maps'],
        ['Webarchive seed', 'webarchive_seed']
    ]
    %>


    <%= form.input :staging_location %>
    <%# the 'staging_style_symlink` is hidden, since we do not currently want users to access it (it may cause problems with some accessioning steps)%>
    <%= form.hidden_field :staging_style_symlink, value: false %>
    <%= form.input :processing_configuration, collection:
        [
            ["Default", "default"],
            ["Group by filename", "filename"],
            ["Group by filename (with pre-existing OCR)", "filename_with_ocr"]
        ]
    %>

    <%= form.input :using_file_manifest, as: :boolean, label: 'I have a file manifest'%>

    <%= form.input :all_files_public,
                   as: :radio_buttons,
                   collection: [['Default', false], ['Preserve=Yes, Shelve=Yes, Publish=Yes', true]] %>

    <%= form.button :submit, class: "btn-sul-dlss" %>
<% end %>

app/views/projects/index.html.erb
<div class="container">
  <h2>Projects History</h2>

  <%= paginate @projects %>

  <table class="table table-bordered">
    <thead>
      <tr class="table-secondary">
        <th scope="col">Name</th>
        <th scope="col">Creator</th>
        <th scope="col">Content Structure</th>
        <th scope="col">Staging Location</th>
        <th scope="col">Processing Configuration</th>
        <th scope="col">Using File Manifest</th>
        <th scope="col"># Job Runs</th>
        <th scope="col">Created At</th>
      </tr>
    </thead>
    <tbody>
    <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.project_name, project %></td>
          <td><%= project.user.email %></td>
          <td><%= project.content_structure %></td>
          <td><%= project.staging_location %></td>
          <td><%= project.processing_configuration %></td>
          <td><%= project.using_file_manifest ? 'yes' : 'no' %></td>
          <td><%= project.job_runs.count %></td>
          <td><%= project.created_at.in_time_zone('Pacific Time (US & Canada)').to_formatted_s(:long) %></td>
        </tr>
    <% end %>
   </tbody>
  </table>

<%= paginate @projects %>
</div>

app/views/projects/new.html.erb
<div class="mt-3">
  <div class="row">
    <section class="col-md-7">
      <%= render "projects/new_bc_form" %>
    </section>
    <section class="col-md-5">
      <ul class="nav nav-pills nav-fill">
        <turbo-frame id="recent-history" src="/job_runs"></turbo-frame>
      </ul>
    </section>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h1><%= @project.project_name %> by <%= @project.user.email %></h1>
    </div>
  </div>
  <div class="row p-1 pl-5">
    <div class="hstack gap-2">
      <%= render partial: 'actions', locals: { project: @project } %>
    </div>
  </div>
  <dl class="dl row">
    <dt class="col-sm-3">Content Structure</dt>
    <dd class="col-sm-9"><%= @project.content_structure %></dd>
    <dt class="col-sm-3">Staging Location</dt>
    <dd class="col-sm-9"><%= @project.staging_location %></dd>
    <dt class="col-sm-3">Processing configuration</dt>
    <dd class="col-sm-9"><%= @project.processing_configuration %></dd>
    <dt class="col-sm-3">Using File Manifest</dt>
    <dd class="col-sm-9"><%= @project.using_file_manifest ? 'yes' : 'no' %></dd>
    <dt class="col-sm-3">Created At</dt>
    <dd class="col-sm-9"><%= @project.created_at %></dd>
  </dl>
  <% if @project.job_runs.present? %>
    <div class="row mt-4">
      <h5>Jobs summary</h5>
      <table class="table">
        <thead>
          <tr>
            <th>JobRun ID</th>
            <th>Type</th>
            <th>Created</th>
            <th>State</th>
          </tr>
        </thead>
        <tbody>
          <% @project.job_runs.each do |job_run|%>
            <tr>
              <td><%= link_to(job_run.id, job_run) %></td>
              <td><%= job_run.job_type.humanize %></td>
              <td><%= job_run.created_at %></td>
              <td><%= job_run.state.humanize %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>

  <% if @project.progress_log_file_exists? %>
    <turbo-frame id="progress-log-frame" src="<%= progress_log_job_run_path(@project.job_runs.last) %>"></turbo-frame>
  <% end %>
</div>